name: sibyl_toolkit

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/sibyl_toolkit.yaml"
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/sibyl_toolkit.yaml"
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"

jobs:
  format:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Format PR title
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          NEW_PR_TITLE=$(echo $PR_TITLE | sed -e 's/^/chore: /')
          echo "New PR title: $NEW_PR_TITLE"
          gh pr edit "$PR_NUMBER" --title "$NEW_PR_TITLE"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1

  spell-check:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1
    with:
      includes: |
        **/*.md
        !brick/**/*.md
        .*/**/*.md
      modified_files_only: false

  verify-version:
    runs-on: ubuntu-latest
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v2

      - name: 🎯 Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: "stable"

      - name: 📦 Install Dependencies
        run: |
          dart pub get

      - name: 🔎 Verify version
        run: dart run test --run-skipped -t version-verify
